import Head from 'next/head';
import { useEffect, useState } from 'react';
import ReactPlayer from 'react-player';

export default function Home() {
  const [hasWindow, setHasWindow] = useState(false);
  const [url, setURL] = useState('');
  const [playerURL, setPlayerURL] = useState(
    'https://livesim.dashif.org/livesim/chunkdur_1/ato_7/testpic4_8s/Manifest.mpd'
  );

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setHasWindow(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: 'flex',
          alignItems: 'center',
          flexDirection: 'column',
        }}
      >
        <h1>URL</h1>
        <input onChange={(e) => setURL(e.target.value)} />
        <button onClick={() => setPlayerURL(url)}>Play</button>
        {hasWindow && <ReactPlayer url={playerURL} controls />}
      </main>
    </>
  );
}
